/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/scout.ts
 * Command: astryx theme build src/theme/scout.ts
 * Generated: 2026-07-16T15:53:23.692Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const scoutTheme: DefinedTheme;
